; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D CORE_DEBUG_LEVEL=5
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/Adafruit NeoPixel@^1.15.5
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	chris--a/Keypad@^3.1.1
	adafruit/Adafruit TCA8418@^1.0.2
	plerup/EspSoftwareSerial@^8.2.0
